server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: superchen_network


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.23.42.66:3306/search?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: chen2726225713


  # 邮箱配置
  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 2726225713@qq.com # 登录qq邮箱的账号
    password: mqfnzbqsrwtpdehe  # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
    default-encoding: UTF-8
    port: 587
  # redis配置
  redis:
    host:  172.23.42.66  #本地IP 或是 虚拟机IP
    password: chen2726225713
    port: 6379
    cache:
      redis:
        time-to-live: 1800000  # 设置缓存数据的过期时间，30分钟
    database: 0  # 默认使用 0号db



mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID
#    # 设置逻辑删除（也可不写，如果逻辑和如下一样，可以不写的）
#    logic-delete-value: 1
#    logic-not-delete-value: 0
