server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: superchen_network
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.67.99:3306/search?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxx


  # 邮箱配置
  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 2726225713@qq.com # 登录qq邮箱的账号
    password: xx  # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
    default-encoding: UTF-8
    port: 587
  redis:
    # 数据库（默认为0号库）
    # database: 2
    #操作redis需要使用的密码
#    password: chen2726225713
    # 端口号
    #    port: 6379
    #连接超时时间（毫秒）
    timeout: 10000ms
    sentinel:
      master: mymaster
      nodes: 115.126.50.127:26379

      # 操作sentinel时需要提供的密码
      password: xx
    # 使用lettuce配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


redisson:
  masterName: mymaster
  schema: redis://
  sentinelAddresses: 115.126.50.127:26379
  password: x

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID
#    # 设置逻辑删除（也可不写，如果逻辑和如下一样，可以不写的）
#    logic-delete-value: 1
#    logic-not-delete-value: 0

